DependsOn implementation
gaia-pipeline/gosdk pull request #2
Opened 2018-08-06 17:32 UTC by michelvocks

2018-08-09 20:21 UTC, Skarlso requested changes
Some things I don't get. :D

2018-08-09 20:21 UTC, Skarlso commented on job.go
> +	"github.com/michelvocks/protobuf"
Is this intended?

2018-08-09 20:21 UTC, Skarlso commented on sdk.go
> +	"github.com/michelvocks/protobuf"
here as well

2018-08-09 20:21 UTC, Skarlso commented on sdk.go
> +				for _, currJob := range j {
There is something fishy here. Aren't you already going through `j` ATM in there is `job` which is currentjob?

2018-08-10 06:14 UTC, michelvocks commented on job.go
> +	"github.com/michelvocks/protobuf"
Yes otherwise I cannot use it currently to test pipeline builds for pipeline parameters. Need to remove it before merge.

2018-08-10 06:17 UTC, michelvocks commented on sdk.go
> +				for _, currJob := range j {
Yes but here I try to find the hash of the `title` of the dependent jobs. That is why I need to loop the jobs again.

2018-08-11 06:54 UTC, Skarlso approved these changes
LGTM! I don't have a better method of doing the dependency check right now. And I don't want to stall this any longer. It does work, so lets iterate on this further at a later time. :)

2018-08-11 06:54 UTC, Skarlso commented on server_listener.go
> +	ok := certPool.AppendCertsFromPEM(rootCert)
This can be streamlined to `if ok := certPool.AppendCertsFromPEM(rootCert); !ok {...`

2018-08-12 10:31 UTC, merged